fabric8-services/fabric8-auth

cico_setup.sh

so that @vpavlin can proceed ;)
https://ci.centos.org/view/Devtools/job/devtools-fabric8-auth-build-master/1/console

disable code analysis temporarily

---

log/log.go

See https://github.com/fabric8-services/fabric8-wit/pull/1536

Add the http properties to our log errors when possible

---

login/service.go

Related to #19 and https://github.com/fabric8-services/fabric8-auth/pull/23

fix link callback URLs

---

.codecov.yml

See https://github.com/fabric8-services/fabric8-wit/pull/1553

ignore the design package from coverage

---

controller/user.go
controller/users.go
jsonapi/error_handler.go
jsonapi/jsonapi_utility.go
jsonapi/jsonapi_utility_blackbox_test.go
login/service.go

See https://github.com/fabric8-services/fabric8-wit/pull/1549

Add req_id to the jsonapi error handler

---

controller/login.go

fixes #42 to adapt to https://github.com/fabric8-services/fabric8-auth/commit/32cc066350e04d5a16a218e918617d5926d9777a

Adapt new endpoint for redirect url during login

---

log/log_request.go

See https://github.com/fabric8-services/fabric8-wit/pull/1560

Update to log duration without unit for plotting

---

auth/authz.go
space/authz/authz.go

Backport of https://github.com/fabric8-services/fabric8-wit/commit/c3d9acdb1d9b64ce29ff6e9c06ebe31c8a4e3880

Limit the number of entitlements

---

auth/resource.go
controller/collaborators_blackbox_test.go
controller/space.go
controller/space_blackbox_test.go
design/account.go
design/spaces.go

Part of https://github.com/fabric8-services/fabric8-auth/issues/27

Return Keycloak Resource when creating a space

---

auth/resource.go
controller/space.go

Related to https://github.com/fabric8-services/fabric8-auth/issues/27

Fix space resource removal

---

.make/Makefile.lnx
.make/Makefile.win
.make/test.mk
Jenkinsfile
Makefile
cico_setup.sh
glide.lock
glide.yaml

Fixes https://github.com/fabric8-services/fabric8-auth/issues/86

get a working release pipeline for fabric8 platform

---

configuration/configuration.go
controller/search.go
controller/search_user_blackbox_test.go

Fixes https://github.com/fabric8-services/fabric8-auth/issues/98

Limit users search result

---

controller/users.go
controller/users_blackbox_test.go
design/account.go

Remove registration complete filter

---

controller/users.go

fix panic when user not found

---

openshift/auth.app.yaml
openshift/auth.config.yaml

Reverts fabric8-services/fabric8-auth#118

Revert "Remove redirect URL from OS template"

---

configuration/configuration.go
configuration/configuration_whitebox_test.go

As a temporal solution to unblock local forge development

allow localhost for redirects by default

---

controller/collaborators.go
controller/collaborators_blackbox_test.go

Instead of checking if the user is the only collaborator in the space we should check if the user is the space owner.

Space onwer should not be allowed to be removed from the list of collaborators

---

controller/login_blackbox_test.go
controller/token.go
login/service.go
login/service_blackbox_test.go
login/service_whitebox_test.go
test/token/token.go
token/token.go
token/token_test.go

Check token claims if user is approved

---

.make/test.mk
Dockerfile.builder
Jenkinsfile

See https://github.com/fabric8-services/fabric8-wit/pull/1674

Reduce test output to minimum

---

README.adoc

Change golang requirements from 1.7 to 1.8 in Readme

---

application/application.go
controller/user_test.go
gormapplication/application.go
migration/migration.go
migration/sql-files/008-rename-token-table.sql
token/provider/external_provider_token.go
token/provider/external_provider_token_blackbox_test.go

Modified table and identifiers in the code to the new term.

rename ExternalProviderToken to ExternalToken

---

application/repository/exister.go
controller/token.go
controller/token_storage_blackbox_test.go
design/token.go
gormsupport/lifecycle.go
gormsupport/lifecycle_blackbox_test.go
gormsupport/lifecycle_hard_delete.go
gormsupport/lifecycle_hard_delete_blackbox_test.go
migration/migration.go
migration/migration_blackbox_test.go
migration/sql-files/009-external-token-hard-delete.sql
token/provider/external_provider_token.go
token/provider/external_provider_token_blackbox_test.go

Fixes https://github.com/fabric8-services/fabric8-auth/issues/138

REST API for removing linked/external tokens

---

.gitignore
.gofmt_exclude
.golint_exclude
.make/test.mk
Makefile
conf/service-account-secrets.conf
configuration/conf-files/service-account-secrets.conf
configuration/configuration.go
configuration/configuration_blackbox_test.go
gormtestsupport/db_test_suite.go
log/log.go
main.go
openshift/auth.app.yaml
openshift/auth.config.yaml

**WIP - There's still some problems with tests that I am working on.**
This PR adds support for configuring service accounts. See #153

ISSUE-153 Allow service accounts to be configured

---

.gitignore
Makefile
account/init_tenant.go
account/init_tenant_whitebox_test.go
configuration/configuration.go
controller/user.go
glide.lock
glide.yaml
main.go
openshift/auth.app.yaml
openshift/auth.config.yaml

UI is now using Auth to call /user so we need to init tenant service in Auth now instead of relaying on WIT /user

Init tenant when /user is called

---

controller/token.go
controller/token_storage_blackbox_test.go

We should try to load the token from Auth DB if Keycloak fails for any reason. Not just 401.
Fixes https://github.com/openshiftio/openshift.io/issues/1379

Retrieve external token from Auth DB if Keycloak failed 

---

goamiddleware/doc.go
goamiddleware/jwt_token_context.go
main.go

Based on https://github.com/fabric8-services/fabric8-wit/pull/1555

Added goa middleware to extract the token when present

---

account/init_tenant.go
auth/authz.go
controller/token.go
login/profile.go
login/service.go
rest/url.go
token/keycloak/external_token.go
token/token.go
wit/wit.go

Fixes https://github.com/fabric8-services/fabric8-auth/issues/204

Close http connections to prevent FDs leaks

---

controller/token.go
controller/token_storage_blackbox_test.go
design/token.go

Add support for 
`/api/token?force_pull=true&for=https://github.com`

Add option to pull externally linked account details

---

README.adoc

Clean up Readme

---

application/application.go
authorization/resource/resource.go
authorization/resource/resource_blackbox_test.go
authorization/resource/resource_type.go
authorization/role/identity_role_blackbox_test.go
controller/resource.go
controller/resource_blackbox_test.go
controller/token_blackbox_test.go
controller/user_test.go
design/resource.go
gormapplication/application.go
token/token.go
token/token_whitebox_test.go

Still need to add some tests... this endpoint won't be fully functional until PAT support is implemented.

ISSUE-71 initial endpoint implementation for resource registration

---

controller/users.go
design/account.go

Follow up on https://github.com/fabric8-services/fabric8-auth/pull/237
Part of https://github.com/fabric8-services/fabric8-auth/issues/241

Use camel case for emailPrivate attribute

---

controller/token.go
login/service.go
login/service_blackbox_test.go

Fixes https://github.com/fabric8-services/fabric8-auth/issues/247

Unapproved users are not redirected to reg app when trying to login

---

openshift/auth.app.yaml
openshift/auth.config.yaml

We need this in our template so we can configure prod.
Do not merge until we have this CM in preview and prod!
fixes https://github.com/fabric8-services/fabric8-auth/issues/257

Add verify email url to openshift template

---

authorization/resource/resource.go
authorization/resource/resource_blackbox_test.go
authorization/role/identity_role_blackbox_test.go
controller/resource.go
controller/resource_blackbox_test.go
design/resource.go

Implement update and delete resource endpoints

---

docs/debugging.html
docs/developer.html
docs/getting-started-win.html
docs/index.html
docs/reference.html
docs/source/reference.adoc

Offline token documentation

---

migration/migration.go
migration/migration_blackbox_test.go
migration/sql-files/018-convert-user-feature-level.sql
migration/sql-test-files/018-convert-user-feature-level.sql

Update content in DB and test migrated data.
Fixes openshiftio/openshift.io#1962

DO NOT MERGE YET - Update user profile to convert remaing `nopreproduction` to `released` (OSIO#1962)

---

docs/reference.html

The doc sources were changed but the html was not re-built. Fixing this.

Build docs from sources

---

controller/token.go
controller/token_blackbox_test.go
login/service.go

tests for `/token/refresh` and POST `/token` with `grant_type=refresh_token`

---

authorization/resource/resource.go
authorization/resource/resource_blackbox_test.go
authorization/role/identity_role_blackbox_test.go
controller/resource.go
controller/resource_blackbox_test.go
migration/migration.go
migration/sql-files/019-authorization-part-2.sql

Fixes #301 
Database migration scripts to prepare schema for new authorization features.

ISSUE-301 migration script for new authorization features

---

goamiddleware/jwt_token_context.go
token/token.go

Extract an interface for the parsing of tokens (OSIO#2091)

---

token/token.go

Include the 'PublicKeys()' method in the 'token.Parser' interface (OSIO#2091)

---

docs/reference.html
docs/source/reference.adoc

Some OpenID Connect and OAuth2 docs cleanup

---

openshift/auth.app.yaml
openshift/auth.config.yaml

Related to https://github.com/fabric8-services/fabric8-auth/issues/337

Add SENTRY_DSN env var

---

gormsupport/cleaner/db_clean.go

Support multiple Primary Keys in DB Cleaner

---

configuration/conf-files/service-account-secrets.conf
configuration/conf-files/tests/service-account-missing-expected.conf
configuration/configuration.go
controller/clusters.go
controller/clusters_blackbox_test.go
controller/token.go
controller/token_storage_blackbox_test.go
token/token.go

Do not merge until https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1474 is done.

Add Jenkins Proxy SA and allow it accessing Cluster & Token APIs

---

controller/users.go
controller/users_blackbox_test.go
design/account.go
login/service.go
test/login.go

Made this a `POST` request because it creates a new verification code and sends out an email.
```
POST /api/users/verificationcode
```
fixes #369

API to trigger verification email

---

openshift/auth.app.yaml

Part of https://github.com/fabric8-services/fabric8-auth/issues/391

Set replica count on Auth DC via saas-heerder

---

controller/users.go

See https://github.com/openshiftio/openshift.io/issues/2687 for more details

Don't return JSONErrorResponce inside transactions

---

controller/users_blackbox_test.go

Disable checks on last-modified values

---

login/service.go
login/service_blackbox_test.go
migration/migration.go
migration/migration_blackbox_test.go
migration/sql-files/025-fix-feature-level.sql
migration/sql-test-files/025-before-fix-feature-level.sql

fixes prod-preview specific issue https://github.com/openshiftio/openshift.io/issues/2692

when new user is being pulled from keycloak, set as RELEASED

---

auth+pmcd.sh

Adapt to https://sourceware.org/git/?p=pcpfans.git;a=commitdiff;h=1f0a1f90bc8e01b5b28810ecd6a8cf505969f243

fix pcp pmdaprometheus configuration line

---

application/application.go
authorization/organization/model/organization_model_service.go
authorization/organization/model/organization_model_service_blackbox_test.go
authorization/organization/service/organization_service_blackbox_test.go
authorization/permission/model/permission_model_service_blackbox_test.go
authorization/repository/repository.go
authorization/role/identityrole/doc.go
authorization/role/identityrole/repository/doc.go
authorization/role/model/role_management_model_service.go
authorization/role/repository/identity_role.go
authorization/role/repository/identity_role_blackbox_test.go
authorization/role/service/role_management_service.go
authorization/role/service/role_management_service_blackbox_test.go
controller/resource_roles.go
controller/resource_roles_blackbox_test.go
gormapplication/application.go
test/authorization.go

Move `authorization/role/identityrole/repository/*` to `authorization/role/repository/`

flatten identityrole repository code into role/repository

---

.make/docker.mk
Dockerfile.deploy.rhel
cico_setup.sh

Enable build on RHEL if TARGET=rhel

Build on RHEL

---

login/oso_reg_app_blackbox_test.go
test/http.go
token/jwk/fetch_keys.go
token/jwk/fetch_keys_blackbox_test.go

It's follow up on https://github.com/fabric8-services/fabric8-auth/pull/435

Tests for key fetcher

---

account/repository/identity.go
account/repository/user.go
account/repository/user_blackbox_test.go
account/repository/verification_code.go
authorization/invitation/repository/invitation.go
authorization/invitation/repository/invitation_blackbox_test.go
authorization/resource/repository/resource.go
authorization/resourcetype/repository/resource_type.go
authorization/resourcetype/repository/resource_type_blackbox_test.go
authorization/resourcetype/repository/resource_type_scope.go
authorization/resourcetype/repository/resource_type_scope_blackbox_test.go
authorization/role/repository/identity_role.go
authorization/role/repository/role.go
authorization/role/repository/role_blackbox_test.go
authorization/role/repository/role_mapping.go
authorization/role/repository/role_mapping_blackbox_test.go
token/provider/external_provider_token.go

Return error if object not found when deleting

---

authorization/authorization.go
authorization/authorization_blackbox_test.go
authorization/invitation/repository/invitation_blackbox_test.go
authorization/invitation/service/invitation_service.go
authorization/invitation/service/invitation_service_blackbox_test.go
authorization/organization/service/organization_service.go
authorization/organization/service/organization_service_blackbox_test.go
authorization/role/repository/role_blackbox_test.go
authorization/role/service/role_management_service_blackbox_test.go
authorization/team/service/team_service_blackbox_test.go
controller/invitation_blackbox_test.go
controller/organization.go
controller/organization_blackbox_test.go
controller/team_blackbox_test.go
migration/migration.go
migration/migration_blackbox_test.go
migration/sql-files/031-clean-up-roles-scopes.sql
test/graph/space_wrapper.go
test/graph/team_wrapper.go

Fixes #501 
Cleans up various roles and scopes.  Still need to add some migration testing.

Cleaned up roles and scopes

---

application/service/services.go
authorization/authorization.go
authorization/authorization_blackbox_test.go
authorization/resource/repository/resource_blackbox_test.go
authorization/resource/service/resource_service_blackbox_test.go
authorization/role/repository/identity_role.go
authorization/role/repository/identity_role_blackbox_test.go
authorization/role/repository/role.go
authorization/role/repository/role_blackbox_test.go
authorization/role/service/role_management_service.go
authorization/role/service/role_management_service_blackbox_test.go
authorization/space/service/space_service_blackbox_test.go
controller/collaborators.go
controller/collaborators_blackbox_test.go
controller/resource_roles.go
controller/resource_roles_blackbox_test.go
controller/space_blackbox_test.go
design/collaborators.go
design/role.go
errors/errors.go
errors/errors_blackbox_test.go
gormtestsupport/db_test_suite.go
test/graph/organization_wrapper.go
test/graph/resource_wrapper.go
test/graph/space_wrapper.go
test/graph/team_wrapper.go
test/graph/test_graph.go
test/graph/user_wrapper.go

Fixes https://github.com/fabric8-services/fabric8-auth/issues/511

Assign/Remove collaborator role when adding/removing space contributors

---

configuration/conf-files/service-account-secrets.conf
configuration/configuration.go
token/token.go

Ready for review/approval but do not merge until we update the secrets in preview and prod.

Service Account for Analytics Gemini Service

---

account/repository/identity.go
account/repository/identity_blackbox_test.go
application/service/services.go
authorization/invitation/repository/invitation.go
authorization/invitation/repository/invitation_blackbox_test.go
authorization/invitation/service/invitation_service.go
authorization/invitation/service/invitation_service_blackbox_test.go
configuration/configuration.go
controller/invitation.go
controller/invitation_blackbox_test.go
design/invitation.go
test/graph/invitation_wrapper.go

Fixes #531 
This PR adds a new endpoint for accepting an invitation.

Implement accept invitation endpoint

---

authorization/invitation/service/invitation_service.go
authorization/invitation/service/invitation_service_blackbox_test.go

Followup on https://github.com/fabric8-services/fabric8-auth/pull/607

Use accept invitation api path from client

---

controller/resource_roles_blackbox_test.go
design/role.go

enforce JWT requirement at design level

---

docs/reference.html
docs/source/reference.adoc

fixes https://github.com/openshiftio/openshift.io/issues/4029

Add docs on how to validate a token

---

account/repository/identity_blackbox_test.go
authorization/permission/service/permission_service_blackbox_test.go
controller/collaborators_blackbox_test.go
controller/invitation_blackbox_test.go
controller/resource_roles_blackbox_test.go
test/graph/identity_wrapper.go
test/graph/organization_wrapper.go
test/graph/resource_wrapper.go
test/graph/test_graph.go

refactor TestInvitationController and TestCollaboratorsController to use subtests
with a new test graph for each test.
Fixes #615

Fix random test failures

---

authorization/resource/repository/resource_blackbox_test.go
test/graph/resource_type_wrapper.go
test/graph/resource_wrapper.go

Avoid using space and organization types
Fixes #638

Improve data isolation in tests

---

application/service/services.go
authorization/invitation/invitation.go
authorization/invitation/service/invitation_service.go
authorization/invitation/service/invitation_service_blackbox_test.go
controller/invitation.go

fix(#642): move redirect params to invitation DAO

---

configuration/configuration.go

Corrected documentation of `GetUserAccountPrivateKey`

docs: correct code documentation

---

configuration/defaults.go
login/service_blackbox_test.go

To ensure http://rhche-dfestal-preview-che.devtools-dev.ext.devshift.net/something works

Add updated devcluster redirect url

---

controller/token.go
controller/token_blackbox_test.go

* Creating user and identity in DB for the first time in developer mode for dev user
Fixes: #674

fix(#674): create token for dev user in developer mode

---

configuration/configuration.go
test/data/cluster/cluster_get_error.yaml
test/data/cluster/cluster_get_ok.yaml

Fix default cluster service URL

---

application/application_db_calls_bench_test.go
application/transaction/transaction_bench_test.go
application/transaction/transaction_test.go
gormtestsupport/benchmark/db_bench_suite.go

Fix compilation errors on bench tests

---

README.adoc
controller/users_blackbox_test.go
login/service.go
login/service_blackbox_test.go
login/service_login_blackbox_test.go

* Remove calling create a user in WIT for first time login
* Update/Fix tests
* Add docs to create a user for development setup using SA account
Fixes: #684

fix(#684): remove create wit user for first time login

---

login/service.go
login/service_login_blackbox_test.go

fixes #695 , https://github.com/redhat-developer/rh-che/issues/839

If fragment already present, return it

---

login/service.go
login/service_login_blackbox_test.go
login/service_whitebox_test.go

fixes https://github.com/fabric8-services/fabric8-auth/issues/698

Dont carry over params as fragments

---

docs/debugging.html
docs/developer.html
docs/getting-started-win.html
docs/index.html
docs/reference.html
docs/source/reference.adoc

This PR puts in the just enough information for a resource server to meaningfully consume the Audit Token endpoint, while explaining the context around it, for determining the user's scope associated with a resource.
fixes https://openshift.io/openshiftio/Openshift_io/plan/detail/52

Docs for consuming RPT tokens/endpoint

---

Makefile
cico_build_deploy.sh
cico_setup.sh

Depends on #https://github.com/openshiftio/openshiftio-cico-jobs/pull/875

chore: call generate_client_setup before deployment of master

---

openshift/auth.app.yaml

This PR fixes incorrect whitespace in this file.  Fixes #730

fix formatting in openshift/auth.app.yaml

---

Gopkg.lock
Gopkg.toml

See https://github.com/fabric8-services/fabric8-common/pull/80

Update common to fix proxy

---

cluster/service/cluster_blackbox_test.go

Currently the test throws a panic if it fails.
This PR fixes the panic.

Fix cluster tests

---

Gopkg.lock
Gopkg.toml
Makefile
cluster/cache.go

* Removes fabric8-cluster dependency
* Adds fabric8-cluster-client dependency

fix: remove fabric8-cluster dependency

---

Dockerfile.builder
Makefile

See https://github.com/openshiftio/openshift.io/issues/4618
Also updates dep to 0.5.0

Switch build to epel release

---

application/service/services.go
authentication/account/repository/identity.go
authentication/account/repository/identity_blackbox_test.go
authentication/account/repository/user.go
authentication/account/repository/user_blackbox_test.go
authentication/account/service/user.go
authentication/account/service/user_blackbox_test.go
controller/users.go
controller/users_blackbox_test.go

feat(#747): rollback transaction to create user and identity when failed to link identity to cluster

---

Gopkg.lock

chore: update lock file

---

migration/migration.go
migration/sql-files/042-token-index.sql

Fixes #763 
This PR should fix performance issues with the `TOKEN` table.

Add index to TOKEN.IDENTITY_ID database column

---

Gopkg.lock
migration/migration.go
migration/migration_blackbox_test.go
migration/sql-files/043-add-admin-console-resource.sql

* Creates resource for admin console. Fixes #768 
* Renames `user_admin` role to `admin_console_admin`. Fixes #769

Create resource for  admin console 

---

docs/debugging.html
docs/developer.html
docs/getting-started-win.html
docs/index.html
docs/reference.html
docs/source/reference.adoc

Reference documentation updated to reflect that offline tokens are no longer supported.

update docs to reflect no further support for offline tokens

---

Gopkg.lock
authentication/account/service/user.go
authentication/account/service/user_blackbox_test.go
authorization/token/manager/token_manager.go
authorization/token/token.go
controller/users.go

Revoke tokens upon user deactivation

---

Gopkg.lock
authentication/account/service/user.go
authentication/account/service/user_blackbox_test.go
test/account.go
test/graph/test_graph.go
test/graph/user_wrapper.go

also include changes in the `testgraph` to be able to retrieve soft-deleted records
fixes #778

soft-delete account during user deactivation

---

authentication/account/service/user.go
authentication/account/service/user_blackbox_test.go
authentication/provider/factory/linking_provider_factory.go
authorization/token/repository/external_provider_token.go
authorization/token/repository/external_provider_token_blackbox_test.go
test/graph/external_token_wrapper.go
test/graph/test_graph.go

delete external tokens during user deactication

---

Makefile
application/service/factory/service_factory.go
authentication/provider/service/authentication_provider_service_blackbox_test.go
authorization/invitation/service/invitation_service_blackbox_test.go
authorization/token/token.go
controller/invitation_blackbox_test.go
controller/namedusers.go
controller/namedusers_blackbox_test.go
controller/token_blackbox_test.go
controller/users_blackbox_test.go
design/namedusers.go
test/clusterservice.go
test/graph/organization_wrapper.go
test/witservice.go

using mocks to verify that controller calls the UserService
also, make sure that all mocks are generated in `test/generated` pkg
fixes #780
* Please describe what your change is about.
* What issues does it solve? (Use [autoreferencing for this](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests))
* If you are still working on the change please prefix the pull request title with "WIP"

expose endpoint to deactivate user

---

migration/migration.go
migration/migration_blackbox_test.go
migration/sql-files/046-identity-last-active-default.sql
migration/sql-test-files/046-identity-last-active-default.sql

Only update null values
Also make sure that new values do not have an empty value from now on.
Fixes #ODC184

Set default value on all empty `last_activity` records

---

Gopkg.lock
application/service/services.go
authentication/account/repository/identity.go
authentication/account/service/user.go
authentication/account/service/user_blackbox_test.go

list identities to deactivate

---

cluster/service/cluster_blackbox_test.go
configuration/conf-files/service-account-secrets.conf
configuration/configuration.go

This PR adds SA configuration to support local development setup for toolchain-operator

Add local dev configuration option for toolchain-operator

---

controller/namedusers.go

log when a user is banned/deprovisioned

---

authentication/account/repository/identity.go
authentication/account/repository/identity_blackbox_test.go
authentication/account/service/user.go
authentication/account/service/user_blackbox_test.go
notification/notification.go

fix expiry date field and check notification msg in tests

---

.make/test.mk
authentication/account/service/user.go
authentication/account/service/user_blackbox_test.go
configuration/configuration.go
configuration/defaults.go
main.go

https://jira.coreos.com/browse/ODC-146
This PR enables step 2 of the testing plan described in the above issue.
Still to-do: limit the user deactivation list to a pre-selected list of e-mail addresses.

Temporary config change / enable workers for testing

---

configuration/configuration.go
configuration/defaults.go
main.go

return values in seconds rather than minutes
Fixes #ODC589

refactor worker interval config

---

configuration/configuration.go
configuration/defaults.go
main.go

New configuration for easier disabling/enabling workers

Configuration for enabling deactivation workers

---

main.go
worker/worker.go

attempt to obtain a lock at each cycle, but
only release during shutdown
fixes #ODC625

refactor deactivation worker locking

---

authentication/account/service/user_blackbox_test.go

Improve tests

---

authentication/account/worker/user_deactivation_notification_worker.go
authentication/account/worker/user_deactivation_worker.go
authentication/subscription/service/oso_subscription_service.go

More logs for user deactivation

---

Gopkg.lock
configuration/defaults.go

As preparation for enabling notification & deactivation in prod.

Set deactivation inactivity period to 7 days after notification

---

Gopkg.lock
Gopkg.toml
authentication/account/service/user.go
authentication/account/service/user_blackbox_test.go
main.go
metric/metric.go
metric/metric_test.go

fixes #ODC622
* Please describe what your change is about.
* What issues does it solve? (Use [autoreferencing for this](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests))
* If you are still working on the change please prefix the pull request title with "WIP"

record metrics for deactivations

---

authentication/account/service/user.go
authentication/account/service/user_blackbox_test.go
authentication/account/worker/user_deactivation_notification_worker_test.go
configuration/configuration.go
configuration/defaults.go
metric/metric_test.go

We don't really need this delay anymore.

Remove delay between notifications

---

Gopkg.lock
authentication/account/service/user.go
authentication/account/service/user_blackbox_test.go
authentication/account/worker/user_deactivation_worker_test.go
authentication/provider/service/authentication_provider_service_blackbox_test.go
authentication/subscription/service/oso_subscription_service_blackbox_test.go
che/service/che_service_blackbox_test.go
cluster/service/cluster_blackbox_test.go
controller/namedusers.go
controller/namedusers_blackbox_test.go
controller/users_blackbox_test.go
notification/service/notification_whitebox_test.go

When we ban users we should also clean up che workspaces.
TODO:

Clean up che when banning users

---

authentication/account/service/user.go
authentication/account/service/user_blackbox_test.go

* Please describe what your change is about.
* What issues does it solve? (Use [autoreferencing for this](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests))
* If you are still working on the change please prefix the pull request title with "WIP"

ignore error when audit log creation failed

---

openshift/auth.app.yaml

add env vars to configure the pods with the config map

---

Makefile
controller/user_service.go
controller/user_service_test.go
main.go

This PR fixes the user service controller constructor.  
Related issue: https://github.com/redhat-developer/rh-che/issues/1409

Fix user service controller constructor

---

.make/Makefile.lnx
.make/Makefile.win
Gopkg.lock
Gopkg.toml
Makefile
openshift/auth.app.yaml

Fix cpu format

---

configuration/configuration.go

Instead of the current 5 minutes

Update cluster cache every 30 seconds

---

configuration/defaults.go

Set oauth state reference cleanup interval to 1 minute
