controller/login.go, controller/login_blackbox_test.go, design/login.go
If `scope=offline_access` param is added to the authentication request then the offline token will be issued instead of a regular refresh token.
Example: `auth.openshift.io/api/login?scope=offline_access`
Related to https://github.com/fabric8-services/fabric8-auth/issues/69
=> Support offline token generation

controller/space.go
We have to temporary ignore DELETE /spaces/:spaceID requests if there is no space with such ID. It may happen if it's an old space created before https://github.com/fabric8-services/fabric8-auth/issues/27
We should revert this change when https://github.com/fabric8-services/fabric8-auth/issues/75 is done.
=> Temporary ignore space resource delete for unknown spaces

Dockerfile.dev, Makefile, README.adoc, auth/authz.go
lets add fast way to rebuild a local docker image and use it inside
minikube / minishift
=> add a make target for fast redeployment of a dev build on mini*

README.adoc
1.
The command that was shown earlier would end up in an error
```
$ ./bin/auth-cli generate login -H localhost:8089 --help
Generate a set of Tokens for different Auth levels. NOT FOR PRODUCTION. Only available if server is running in dev mode
Usage:
auth-cli generate [command]
Available Commands:
token       
Global Flags:
--dump               Dump HTTP request and response.
--format string      Format used to create auth header or query from key (default "Bearer %s")
-H, --host string        API hostname (default "openshift.io")
--key string         API key used for authentication
-s, --scheme string      Set the requests scheme
-t, --timeout duration   Set the request timeout (default 20s)
Use "auth-cli generate [command] --help" for more information about a command.
```
2.
fix for
``` …
```
=> Added fix to a troubleshooting problem and changed the command to generate tokens

main.go, space/authz/authz.go, space/authz/authz_test.go
We do not use RPT tokens to authorize a user in spaces anymore. So, this PR removes code that checkes if the access token is an RPT token otherwise calls Keycloak to check entitlement. We should just call Keycloak to obtain an entitlement.
Part of https://github.com/fabric8-services/fabric8-auth/issues/65
=> Clean up space authorization code

remoteservice/wit.go
When creating a new identity in Auth which already exists in WIT we should not set profileURL for such identity in Auth. ProfileURL is returned as an empty string in User's result payload which causes `failed to create user/identity pq: duplicate key value violates unique constraint \"uix_identity_profileurl\"` error in Auth DB. The profileURL should be null. Not an empty string.
We could check if profileURL is an empty sting and insert a null instead but profileURL is not currently used anyway (it's supposed to be used in remote, like GitHub, identities). So, let's just ignore this field in that temporal code.
=> Don't fetch profileURL from WIT

login/service.go, remoteservice/wit.go
Noticed this when 
`http://localhost:8080/api/users?filter[email]=sbose78@gmail.com` kept failing in WIT because the user was created from AUTH without the ProviderType field.
And our DAO code always does a `where provider_type = 'kc'` while fetching data from the db.
=> For new user, add provider type as well

config.yaml, configuration/configuration.go, configuration/configuration_blackbox_test.go, controller/login.go, controller/users.go, controller/users_blackbox_test.go, login/service.go, remoteservice/wit.go
WIT URL can now be set via env var. I also renamed WITEndpoint to WIT URL to avoid confusion because it represents the base WIT URL. Not the final endpoint.
Fixes https://github.com/fabric8-services/fabric8-auth/issues/113
=> Make WIT URL configurable via env var

configuration/configuration.go, configuration/configuration_whitebox_test.go, controller/link.go, controller/login.go, controller/logout.go, login/logout_blackbox_test.go, login/service.go, login/service_blackbox_test.go
Use *.openshift.io as valid redirect URL by default even if the corresponding env var is not set.
=> Use *.openshift.io as valid redirect URL by default

controller/login_blackbox_test.go, controller/token.go, controller/users_blackbox_test.go, login/service.go, login/service_whitebox_test.go, remoteservice/wit.go
We don't need to check the user in WIT during login anymore. Auth DB is now in sync with WIT.
This part of the cleanup phase from - https://github.com/fabric8-services/fabric8-auth/issues/79
=> Stop checking if user exists in WIT during login

auth/authz.go, auth/authz_blackbox_test.go, controller/login_blackbox_test.go, controller/token.go, design/login.go, login/profile_blackbox_test.go, login/service.go, login/service_blackbox_test.go, token/token.go, token/token_test.go
- Added new `/api/login?api_client=<anystring>` param to issue a set of tokens to be used for api calls even if user is not approved yet.
- If `api_client` is present and not an empty string then the token json will be encoded in `api_token` param instead of `token_json`
- If user is not approved then we do not create a new user/identity in the Auth DB.
- Added tests to cover login flow.
It's based on https://github.com/fabric8-services/fabric8-auth/pull/124 (so, contains the same commit) which can be merged separately.
Fixes https://github.com/fabric8-services/fabric8-auth/issues/125
Fixes https://github.com/fabric8-services/fabric8-auth/issues/34
Related to https://github.com/fabric8-services/fabric8-auth/issues/46
=> New "api_client" param for /api/login

application/application_db_calls_bench_test.go, configuration/configuration.go, glide.lock, glide.yaml, log/log.go, log/log_test.go
Switched from github.com/Sirupsen/logrus to github.com/sirupsen/logrus
This commit will probably not build because not all packages that this
project depends on have adopted the lowercase version of the package. We
have to merge this commit anyway, I think.
Also updated GOA to 1.3.0
See also fabric8-services/fabric8-wit#1395
=> sirupsen-case for fabric8-auth

login/service.go, login/service_whitebox_test.go, token/token.go, token/token_test.go
Avoid lower level package dependency on external generated
REST API.
Related to fabric8-services/fabric8-wit#1395
=> Move TokenToJson to service level

.gitignore, controller/users.go, login/service.go, wit/wit.go
IMO it makes sense to keep all wit related code in the wit package instead of spreading it between remoteservices and wit/witservices
=> Move remoteservices/wit.go to wit/wit.go

migration/migration.go, migration/migration_blackbox_test.go, migration/sql-files/007-external-provider-id-index.sql
It doesn't make any sense to convert provider ID to low case because we use UUID as provider IDs
=> External token provider ID index should be case sensitive

controller/token_blackbox_test.go, design/token.go, token/link/link.go, token/link/link_test.go
`for` can now contains a set of resources separated by comma.
For example: `/api/token/link?for=https://github.com,https://api.openshift.com`
Fixes https://github.com/fabric8-services/fabric8-auth/issues/159
=> Support multiple resources when linking accounts

auth/authz.go, controller/token.go
* Please describe what your change is about.
Fix incorrect spellings in `token.go` and `authz.go`. 
`responce` => `response` and `toke` => `token`
=> Fix minor typos in token.go and authz.go

token/link/link_test.go
Fixes the issue with leftovers in identities table after account linking tests.
=> Clean up test identity in account linking tests

token/token.go, token/token_remote_test.go, token/token_whitebox_test.go
For consistency sake.
We are using github repo name as service account names.
Already updated in WIT - https://github.com/fabric8-services/fabric8-wit/pull/1758 (in prod)
=> Rename auth Service Account to 'fabric8-auth'

account/identity.go, account/user.go, account/user_blackbox_test.go
Made changes such that gorm can update fields with blank values as well
It was treating them as not-changed before
Fixes(#186)
=> Enabling updates to accept empty strings for User's profile for optional fields

controller/token.go, controller/token_storage_blackbox_test.go, main.go, token/keycloak/external_token.go
We should delete the Account links from Keycloak when deleting them via Auth API.
Extracted from https://github.com/fabric8-services/fabric8-auth/pull/155
=> Delete account links from Keycloak

auth/authz_blackbox_test.go, auth/policy_blackbox_test.go, configuration/configuration.go
Keycloak test are very unstable. It seems to be a problem with our Keycloak. This PR introducing a new env var to control Keycloak tests. By default we disable AuthZ tests which call remote Keycloak.
As a long term solution we are working on moving our AuthZ functionality to Auth service instead of relaying unstable Keycloak.
=> Disable KC AuthZ tests

configuration/configuration.go, controller/status_test.go
Currently the deployment fails in preview because we have the valid redirect URL there is different from the default one and prod.
=> Allow to overwrite valid redirect URL in prod and staging env

configuration/configuration.go, controller/search.go, controller/search_user_blackbox_test.go
When user is searched using the API:
this change will ensure that the search string contains at least 1 character in the set A-Z,a-z,0-9
`https://auth.openshift.io/api/search/users?q=@.`  not allowed.
`https://auth.openshift.io/api/search/users?q=bose@` allowed.
=> Add constraint for allowed user search query string

log/log.go
Configuration package includes confbindata.go generated my `make`. So, we can't re-use any code which depends on configuration package in our downstream repos (WIT, tenant, etc). confbindata.go is not available there.
Currently WIT uses design and token packages from Auth. So removing log->configuraton dependency will fix the WIT->Auth/token dependency.
=> Get rid of configuration dependency in logger

controller/token.go, controller/token_blackbox_test.go, controller/users.go, controller/users_blackbox_test.go, design/account.go, login/profile.go, login/profile_user_blackbox_test.go, login/profile_user_whitebox_test.go, rest/url.go, rest/url_blackbox_test.go, token/token.go, token/token_whitebox_test.go
If during creating a new user by the registration app the user already exists in Keycloak then we should update the user in Keycloak.
If user already exists in the Auth DB then return 409 Conflict.
Fixes https://github.com/fabric8-services/fabric8-auth/issues/230
=> Update existing Keycloak users when registering new users

controller/user_test.go
Tests weren't running since TestRunUserREST() was defined as a method of TestUserREST. Two failing tests are yet to be fixed
```
=== RUN   TestCurrentAuthorizedNotModifiedUsingIfModifiedSinceHeader
--- FAIL: TestCurrentAuthorizedNotModifiedUsingIfModifiedSinceHeader (0.00s)
user_testing.go:236: invalid response status code: got 200, expected 304
=== RUN   TestCurrentAuthorizedNotModifiedUsingIfNoneMatchHeader
--- FAIL: TestCurrentAuthorizedNotModifiedUsingIfNoneMatchHeader (0.00s)
user_testing.go:236: invalid response status code: got 200, expected 304
```
#232
=> Fixing tests for /user

account/user.go, controller/collaborators.go, controller/search.go, controller/search_user_blackbox_test.go, controller/user.go, controller/user_test.go, controller/users.go, controller/users_blackbox_test.go, design/account.go, migration/migration.go, migration/sql-files/012-hide-email.sql, test/account.go
Fixes https://github.com/fabric8-services/fabric8-auth/issues/35
The objective of this PR is to provide a way to make email private using the `PATCH /api/users`
Make your email private : 
```
curl --request POST \
--url http://localhost:8089/api/users \
--header 'authorization: Bearer eyJhbGciOiJSUzI1NiIajg' \
--header 'content-type: application/json' \
--data '{"data": { "attributes": {"email_private":true},"type": "identities"}}'
```
The email should not be returned ( will be an empty string ) when a call similar to 
```
https://auth.openshift.io/api/users?filter[username]=shbose
```
is made.
However, a call to to 
```
curl --request GET \
--url http://localhost:8089/api/user \
--header 'authorization: Bearer eyJhbGciOiJSUzI1NiIajg' \
```
would return the email address irrespective of …
=> Allow email privacy to be configured

controller/users.go, controller/users_blackbox_test.go, design/account.go, login/profile.go, login/profile_user_blackbox_test.go
- when new user is created by online-registration app, `enable` it  and also set `emailVerified=true` *always*.
- when new user is created, make `emailPrivate = false` in order to not deviate from current behavior.
- support passing of the RHD user id in the payload. That would be used for linking.
=> Accept RHD user ID in Create User Payload

configuration/configuration.go, controller/status_test.go
Readiness prob is broken after merging https://github.com/fabric8-services/fabric8-auth/pull/227
We need to add the tenant URL in Config Map first then we can check if it's empty in our readiness prob.
Removing it from the prob until we fix our Config Map.
=> Fix health prob

openshift/auth.app.yaml, openshift/auth.config.yaml
The corresponding configuration needs to be added to the service. 
Note: notification service url is not accessible outside openshift.
=> update template for notification service url

configuration/configuration.go, controller/status_test.go
This reverts commit 6a86faa9bba38361aafd65cc17c665474b7b2970.
Now that the notification service url is configured in both prod-preview/prod, this change is safe to put in.
=> Revert "Disable check for notification url (#244)"

controller/status.go
When /api/status is hit, if there is an error in configuration that causes a 503 - log the error as well.
=> Log configuration error in status probe

configuration/conf-files/service-account-secrets.conf, configuration/configuration.go, configuration/configuration_blackbox_test.go, controller/users.go, controller/users_blackbox_test.go, test/account.go
Partially fixes https://github.com/fabric8-services/fabric8-notification/issues/52
**TODO**
**How to test**
1. Get service account token: 
```
curl --request POST   -d "grant_type=client_credentials&client_id=4c34f6d4-f00b-487b-9a1f-e7d1adba6866&client_secret=secret"  --url http://localhost:8089/api/token  
```
2. Pass token in the request 
```
curl --header "authorization: bearer $token" http://localhost:8089/api/users/7587730b-a4c0-4023-aa3a-dde91a3f5fd5
```
=> Override email privacy using notification service token

account/email/verification_service.go, account/email/verification_service_blackbox_test.go, controller/users.go, controller/users_blackbox_test.go
because the notification service uses the `GET /api/users/<identity-id>` to look up user details.
=> send the identity id instead of user id

controller/users.go, controller/users_blackbox_test.go, rest/url.go, rest/url_blackbox_test.go, test/common.go
- If no there is no error then do not add "error" param
- Encode params so the redirect URL can contain predefined params in configuration. Plus error message can may be not URL friendly.
Fixes https://github.com/fabric8-services/fabric8-auth/issues/258
=> Fix params in email verify redirect URL

controller/users.go
Upon email verification, I'm using the same API we used to create/update user , to update the user.
Not using the user profile Update API because that needs a user token, and in the verification controller, the user token is absent.
=> update keycloak on email verification

controller/token.go, controller/token_storage_blackbox_test.go
So, the new format is `WWW-Authenticate: LINK url=https://auth.openshift.io/api/token/link?for=https://github.com, description=”GitHub token is missing. Link GitHub account”`
=> Add for param to WWW-authenticate header to link accounts

controller/token.go, design/token.go
- Adds `expires_in` to token response. `expires_in` seems to be a standard name for that attribute in OAuth2 and OpenID Connect but some dialects uses expiry. So, let's use both to be safe.
- Some clean up
This is a followup on https://github.com/fabric8-services/fabric8-auth/pull/272 and https://github.com/fabric8-services/fabric8-auth/issues/270
=> Add expires_in to token response. Some cleanup

controller/token.go, controller/token_blackbox_test.go, design/token.go
OAuth2 and OpenID Connect specifies expire_in. Not expiry. Some dialects still use expiry (for example go oauth2 token uses expiry) but we do not have any clients yet which use our authorize and token/refresh endpoints. So, it's safe now to support the OAuth2 and OpenID Connect expire_in attribute only and drop expiry. Especially because we misused expiry attribute. Expiry is supposed to be an int which represents a Unix time stamp. Not a string.
=> Remove expiry

account/user.go, controller/users.go, controller/users_blackbox_test.go, design/account.go, migration/migration.go, migration/sql-files/017-feature-level-not-null.sql, test/account.go
Make the field in the `user` type as a `string` instead of `*string`.
Make the DB column `NOT NULL` in the DB with a default value to `released`,
and update all existing records.
Also, refactored some code to reduce the amount of lines to init user/indentity.
Fixes openshiftio/openshift.io#1937
=> Make the `featureLevel` not optional in the user's profile (OSIO#1937)

controller/collaborators_blackbox_test.go
Calling the endpoint once to get the current `Last-Modified` and `Etag`
response headers, then re-use those values in the subsequent requests
to verify that the server returns a `304 Not Modified` response.
Fixes openshiftio/openshift.io#1986
=> Fix random test failure on `auth` (OSIO#1986)

controller/collaborators_blackbox_test.go, controller/conditional_request_test.go, controller/users_blackbox_test.go
Instead of computing the value of the request header to use
(`If-Modified-Since` or `If-None-Match`), send a request with
no specific header, read the response header and reuse it in a
subsequent request to check that the server responds with a
`304 Not Modified` response. The test does not need to make the
header computation, just verify that the server can process it
as expected.
Fixes #299
=> Fix test failures on conditional request (#299)

configuration/conf-files/tests/oso-clusters-custom-urls.conf, configuration/conf-files/tests/oso-clusters-missing-keys.conf, configuration/configuration.go, configuration/configuration_blackbox_test.go, controller/clusters.go, controller/clusters_blackbox_test.go, design/clusters.go
Two new URLs in cluster config are "console-url' and "metrics-url":
```
GET /api/clusters
{
"data": [
{
"api-url": "https://api.starter-us-east-2.openshift.com",
"app-dns": "8a09.starter-us-east-2.openshiftapps.com",
"console-url": "https://console.starter-us-east-2.openshift.com/console",
"metrics-url": "https://metrics.starter-us-east-2.openshift.com/hawkular/metrics/m/stats/query",
"name": "us-east-2"
}
]
}
```
Fixes https://github.com/fabric8-services/fabric8-auth/issues/302
=> Add console and metrics URLs to /clusters

auth/authz.go, controller/token.go, login/link/keycloak_idp.go, login/profile.go, token/keycloak/external_token.go, token/keycloak/token.go, token/oauth/oauth2.go, token/token.go, wit/wit.go
It seems that we already read the body before we close it but maybe we still miss it somewhere or there is a panic or something else. So just in case let's explicitly read response body when closing it in defer to make sure we are not leaking FDs.
=> Explicitly read response body when closing it to avoid FD leaks

configuration/configuration.go, configuration/configuration_blackbox_test.go, controller/clusters.go, controller/clusters_blackbox_test.go, controller/users.go, controller/users_blackbox_test.go, rest/url.go, rest/url_blackbox_test.go, token/link/link.go, token/link/link_test.go
Regardless of actual URLs we store in user's profile and cluster configuration for OSO API, Console, and Metrics URL we should return these URLs with a trailing slash (for example "https://api.*.openshift.com/")
=> Add trailing slash to user.cluster, APIURL, ConsoleURL, and MetricsURL

goamiddleware/jwt_token_context.go, main.go, token/token.go, token/token_test.go
Regardless of security declaration in goa design definition we should validate all incoming tokens.
For example if we do not require Authorization header in /api/users/:ID we still check the token in case the request is coming from a Service Account. We should validate such tokens anyway.
This PR modifies our logging middleware. Now we not only add all the tokens in the context but also validate them. If there is Authorization header with a bearer token then we will validate it. If token is not valid then 401 will be returned.
=> Validate all incoming tokens

authorization/model/organization_model_service_blackbox_test.go, controller/organization.go, controller/organization_blackbox_test.go, design/organization.go
This is a followup on https://github.com/fabric8-services/fabric8-auth/pull/317
=> WIP More tests for creating and listing orgs

controller/resource_blackbox_test.go, controller/token.go, controller/token_storage_blackbox_test.go, design/token.go, gormsupport/cleaner/db_clean.go, gormtestsupport/db_test_suite.go
```
GET /api/token/status?for=<resource>&force_pull=true|false
Authorization: Bearer <token>
```
Response: `200 OK` - token is present
Response: `401` token is not present or invalid (if force_pull == true)
Fixes https://github.com/fabric8-services/fabric8-auth/issues/312
=> Endpoint to check if an external token is available

minishift/README.md, minishift/kedge/auth-local.yml, minishift/kedge/auth.yml, minishift/kedge/db-auth.yml
Fixes #328 
This PR updates the kedge files to work with the latest version (as of now 0.9.0) of Kedge, and updates `minishift/README.MD` with more specifics about supported version numbers and environments.
```
shane@shane-ThinkPad-W541:~/go/src/github.com/fabric8-services/fabric8-auth$ minishift stop
Stopping local OpenShift cluster...
Cluster stopped.
shane@shane-ThinkPad-W541:~/go/src/github.com/fabric8-services/fabric8-auth$ minishift delete
You are deleting the Minishift VM: 'minishift'. Do you want to continue [y/N]?: y
Deleting the Minishift VM...
Minishift VM deleted.
shane@shane-ThinkPad-W541:~/go/src/github.com/fabric8-services/fabric8-auth$ make dev-openshift
GO15VENDOREXPERIMENT=1 GOARCH=amd64 GOOS=linux go build -o bin/docker/fabric8-auth-linux
minishift start --cpus 4
-- …
```
=> Updated instructions and kedge files for deploying to minishift

controller/token.go, controller/token_storage_blackbox_test.go, design/token.go, main.go, test/account.go, test/oauth.go, token/link/github.go, token/link/link.go, token/link/link_test.go, token/link/openshift.go
This PR adds a special alias for the user's cluster URL - `/api/token?for=openshift`. Auth service looks up for the cluster URL where the user is provisioned to and returns the token for that cluster.
There is also `github` alias available for `https://github.com` - `/api/token?for=github`
```
GET /api/token?for=openshift
Authorization: Bearer <OSIO_USER_TOKEN>
OK 200
{
"access_token": "asdd123213hsd",
"scope": "user:full",
"token_type": "Bearer",
"username": "johnsmith",
"provider_api_url": "https://api.starter-us-east-2.openshift.com"
}
```
```
GET /api/token/status?for=openshift
Authorization: Bearer <OSIO_USER_TOKEN>
200 OK
{
"username": "johnsmith",
"provider_api_url": "https://api.starter-us-east-2a.openshift.com"
}
```
Fixes …
=> Add alias for user's OSO url to /api/token?for=<alias>

controller/token.go, controller/token_storage_blackbox_test.go, test/oauth.go, token/link/link.go, token/link/openshift.go
Currently we support force_pull param in /api/token?for=<oso_resource> endpoint when retrieving user OSO tokens.
This PR also adds support of the same force_pull param for cluster tokens too. Not only for user tokens.
When force_pull=true the auth service will load the user profile using the stored dsaas user token. It will return 401 if the token is not valid and rejected by OSO.
Required for https://github.com/openshiftio/openshift.io/issues/2304
=> Support force_pull for /api/token when retrieving cluster tokens

controller/clusters.go, controller/clusters_blackbox_test.go, controller/token.go, controller/token_storage_blackbox_test.go, token/token.go
So, Jenkins Idler can access cluster configuration and cluster tokens.
=> Add Jenkins-Idler SA to cluster and token API

Dockerfile.builder, Makefile
```
INFO: go version go1.8.3 linux/amd64
INFO: GOARCH=amd64 GOBIN= GOEXE= GOHOSTARCH=amd64 GOHOSTOS=linux GOOS=linux GOPATH=/home/...
```
Based on https://github.com/fabric8-services/fabric8-wit/pull/1935
=> Show Go version when building

configuration/configuration.go, controller/users.go, controller/users_blackbox_test.go
When OSO reg app creates a user with email == `<username>+preview*@redhat.com` then Auth ignores such user.
Such accounts are supposed to be used only in Preview. So there will be no account sharing between prod and preview.
Fixes https://github.com/fabric8-services/fabric8-auth/issues/377
=> Don't create preview OSO accounts in prod OSIO/Auth if they were provisioned for preview env

log/log.go, log/log_request.go, log/log_test.go
* removed dead code (`func NewCustomizedLogger`)
* removed unnecessary and confusing double instantiation of `logger`
* minor fixes hinted by [`gometalinter`](https://github.com/alecthomas/gometalinter)
=> fix: cleans up logging package

authorization/role/model/role_management_model_service.go, authorization/role/model/role_management_model_service_backbox_test.go, authorization/role/service/role_management_service.go, authorization/role/service/role_management_service_blackbox_test.go, controller/resource_roles.go, controller/resource_roles_blackbox_test.go, design/role.go
This API returns all assignees to a specific role, for a specific resource.
Request:
```
GET /api/resources/:resourceID/roles/:roleName
Authorization: Bearer <User OpenShift.io token>
```
A 200OK Response would look like :
```
{
data: [
{
assignee_id: "cb567f71-b09c-4784-a692-9270a6679af8",
assignee_type: "user",
inherited: false,
role_name: "collab"
},
{
assignee_id: "bb577f71-b09c-4784-a692-9270a6679af8",
assignee_type: "user",
inherited: false,
role_name: "collab"
},
{
assignee_id: "af567f71-b09c-4784-a692-9270a6679af8",
assignee_type: "user",
inherited: false,
role_name: "collab"
}
]
}
```
fixes #375
=> Get role assignments for a specific resource & role name

openshift/auth.app.yaml
Restrict how much memory the container can consume.
Limit to avoid it overtaking the cluster if the process were to go rogue.
Related to openshiftio/openshift.io#2685
=> Set resource limits on Container level

configuration/configuration.go, controller/token_storage_blackbox_test.go
Instead of `admin:repo_hook read:org repo user gist`
We will now ask for `admin:repo_hook read:org public_repo read:user`
Part of https://github.com/openshiftio/openshift.io/issues/259
=> Ask for less GitHub permissions when linking OSIO and GitHub

account/identity.go, account/user.go, account/user_blackbox_test.go, controller/collaborators.go, controller/search.go, controller/search_user_blackbox_test.go, controller/users.go, controller/users_blackbox_test.go, design/account.go, design/search.go, gormsupport/cleaner/db_clean.go, jsonapi/jsonapi_utility.go
`/api/users?filter[email]=<email>` and `/api/search/users?q=<email>` look up public emails only.
Fixes https://github.com/fabric8-services/fabric8-auth/issues/387
=> Don't return private emails in user search result

glide.lock, glide.yaml
Not used in the project. Other updates in `glide.yaml`
where triggered by the `glide update` command.
Fixes #406
=> Remove dependency on `go-vcr` #406

authorization/role/repository/role_scope.go, gormsupport/cleaner/db_clean.go
We missed `gorm:"primary_key"` tag for role_scope table, so, GORM didn't set PKs for that table. It resulted to "DELETE FROM role_table" in our db clean func.
=> Fix PK for role_scope table

controller/token.go, controller/token_blackbox_test.go, controller/token_storage_blackbox_test.go, main.go
The user tokens generated are generated by the Auth service and not by keycloak.
Therefore, this PR removes the 'backup' capability of talking to keycloak, in order to retrieve a github/keycloak token if not found in the Auth DB.
fixes #417
=> deprecate fallback token retrieval from keycloak

account/identity.go, migration/migration.go, migration/sql-files/026-identities-users-indexes.sql
Related to #388 
This PR for now addresses the user search DB performance spikes.  The btree indexes on identities.username, users.user_email and users.user_full_name have been dropped, and replaced with trigram indexes that support indexed searches on wildcard LIKE comparisons.  The user search query has been rewritten as a UNION SELECT query in order to take advantage of the new index types, which results in SQL that looks like this:
```
SELECT * FROM (
SELECT 
identities.id AS identity_id,
identities.username,  
users.*
FROM 
identities, users
WHERE 
identities.user_id = users.id 
AND identities.username LIKE '%337827a2-0946-4b11-91a2-b8db22dac9a3%'
AND users.deprovisioned IS false
UNION SELECT
identities.id AS identity_id,
identities.username,
users.*
FROM
identities, users
WHERE …
```
=> restructured user search query, recreated search indexes

authorization/resource/repository/resource.go, authorization/resourcetype/repository/resource_type.go, authorization/resourcetype/scope/repository/resource_type_scope.go, authorization/role/repository/identity_role.go, authorization/role/repository/role.go, authorization/role/repository/role_mapping.go
This is maybe the reason of our failing tests.
Go tags are in key:value format. Declaring multiple keys with the same name you always set only one key value. Not sure which one (maybe it's even random).
If we need to set multiple values then we should use `;`
For example: `gorm:"primary_key;column:invitation_id"`
=> Fix gorm tags

Dockerfile.deploy.rhel
This should have been part of https://github.com/fabric8-services/fabric8-auth/pull/450 ;)
=> Fix golang image path for RHEL Docker file

Gopkg.lock, Jenkinsfile, Makefile, cico_setup.sh
This dependency was added by `dep init` during our migration from Glide to Go Dep and it's currently used only by `analyze-go-code`. We don't really use this lint analyze outputs in our CI builds, so I'm removing it from our ci/cd builds. It also will make our CI build a bit faster.
Currently https://golang.org/x/lint is down and it blocks our build.
=> Remove https://golang.org/x/lint depenency

account/identity_blackbox_test.go, authorization/organization/service/organization_service_blackbox_test.go, authorization/resource/repository/resource.go, authorization/resource/repository/resource_blackbox_test.go, authorization/role/repository/role_mapping_blackbox_test.go, migration/migration.go, migration/migration_blackbox_test.go, migration/sql-files/028-make-organization-names-unique.sql
This PR includes a migration script and tests for updating the database constraints to prevent duplicate organization names.  The migration script will check for any existing duplicate organization names, and update them on a "first created, first served" basis.  I.e. for organization name "Acme", the record with the earliest created_at value will remain unchanged, while subsequent organizations with duplicate names will have their names updated to "Acme (1)", "Acme (2)", etc.
Fixes #358
=> Enforce unique organization names in database

account/identity_blackbox_test.go, authorization/role/repository/role.go
Fixes #463
This PR adds a `deleted_at IS NULL` condition for both the `role` and `resource_type` tables in the SQL for `RoleRepository.FindRolesByResourceType()`.  This should fix the error we sometimes see in the test.
=> Fix intermittent failure of role management service test

account/identity.go, authorization/role/repository/identity_role.go
This PR adds `deleted_at` conditions to both the identity search, and identity_role find permissions queries which both use raw SQL.
Fixes #466
=> Add missing deleted_at conditions to raw queries

application/repository/repositories.go, authorization/permission/service/permission_service_blackbox_test.go, authorization/resourcetype/repository/resource_type_scope.go, authorization/resourcetype/repository/resource_type_scope_blackbox_test.go, authorization/resourcetype/scope/repository/doc.go, authorization/role/repository/identity_role_blackbox_test.go, authorization/role/repository/role.go, authorization/role/repository/role_scope.go, authorization/role/repository/role_scope_blackbox_test.go, authorization/role/service/role_management_service_blackbox_test.go, controller/resource.go, gormapplication/application.go, test/authorization.go
This PR merges the `/authorization/resource_type/scope` directory into `/authorization/resource_type`.
Fixes #462
=> Flattened /authorization/resource_type directory structure

authorization/role/service/role_management_service_blackbox_test.go, test/authorization.go
Fixes #463 (hopefully for good this time)
I believe that because we were using the `openshift.io/resource/area` resource type for this test, that roles created for the same resource type by other tests were getting picked up by the `ListAvailableRolesByResourceType()` method before the db cleanup had a chance to run.
Then, sometime after this method but before the `roleRepo.Load()` call (which happens when the same test calls `checkRoleBelongsToResourceType()` with the list of the roles it had found) the db cleanup gets run.  This means that the `roleRepo.Load()` will then fail when it tries to load one of the roles that got cleaned up.
I've addressed this by creating a unique resource type just for the purpose of this test, which should ensure that db cleanup of other roles for the area …
=> Use unique resource type for role tests

token/provider/external_provider_token.go, token/provider/external_provider_token_blackbox_test.go
If a user has multiple github or OSO tokens in the token storage, then return the tokens in the descending order of `created_at` because the most relevant token would always be the most recent one.
=> return external tokens in descending order of created_at timestamp

application/service/services.go, authorization/resource/repository/resource.go, authorization/resource/service/doc.go, authorization/resource/service/resource_service.go, authorization/resource/service/resource_service_blackbox_test.go, authorization/resourcetype/repository/resource_type.go, controller/resource.go, controller/resource_blackbox_test.go, design/resource.go, errors/errors.go, errors/errors_blackbox_test.go, errors/errors_whitebox_test.go, gormapplication/application.go
This is a prerequisite for https://github.com/fabric8-services/fabric8-auth/issues/366
=> Reorganize resource management

application/service/services.go, authorization/authorization.go, authorization/authorization_blackbox_test.go, authorization/resource/repository/resource.go, authorization/resource/service/doc.go, authorization/resource/service/resource_service.go, authorization/resource/service/resource_service_blackbox_test.go, authorization/resourcetype/repository/resource_type.go, authorization/role/repository/identity_role.go, authorization/role/repository/identity_role_blackbox_test.go, authorization/role/service/role_management_service.go, authorization/role/service/role_management_service_blackbox_test.go, controller/resource.go, controller/resource_blackbox_test.go, controller/resource_roles.go, controller/resource_roles_blackbox_test.go, design/resource.go, design/role.go, errors/errors.go, errors/errors_blackbox_test.go, errors/errors_whitebox_test.go, gormapplication/application.go, test/error.go, test/login.go
replaces #399 
```
PUT /api/resources/:resourceID/roles
Authorization: Bearer <AccessToken>
{
"data": [
{ "role": "admin", "ids": ["<identityID1>"] },
{ "role": "contributor", "ids": ["<identityID2>", "<identityID3>"] },
...
]
}
```
fixes #398
=> Add the "Assign role" API

application/repository/base/exister.go, application/repository/repositories.go, authorization/resource/service/resource_service.go, authorization/resource/service/resource_service_blackbox_test.go, authorization/role/repository/default_role_mapping.go, authorization/role/repository/default_role_mapping_blackbox_test.go, authorization/role/repository/role_mapping.go, authorization/role/repository/role_mapping_blackbox_test.go, controller/resource_roles_blackbox_test.go, gormapplication/application.go, test/graph/default_role_mapping_wrapper.go, test/graph/role_mapping_wrapper.go, test/graph/role_wrapper.go, test/graph/test_graph.go
This PR fixes #472 
Creates role mapping records for resources during resource registration, based on the default role mappings for the resource type.
=> Automatically create role mappings during resource registration

configuration/conf-files/service-account-secrets.conf, controller/collaborators_blackbox_test.go, controller/space.go, controller/space_blackbox_test.go, design/spaces.go
If the space creation API call is made using the `space-migration` service account, then the creator ID is passed as a parameter in the request `/api/spaces/spaceID?creator=creator-uuid`.
In this scenario, there would be no keycloak interactions, or `space_resources` table updation.
This commit can be reverted after migration of spaces is done.
Dependency of #365
=> temporarily support space creation using service account

authorization/resource/repository/resource.go, authorization/resource/repository/resource_blackbox_test.go, authorization/space/service/space_service_blackbox_test.go, controller/space.go, controller/space_blackbox_test.go, design/spaces.go
Return 409 if a space is being created with an existing resource ID
=> Support 409 error for creating a space with existing ID

controller/resource_roles.go, controller/resource_roles_blackbox_test.go
During migration, the script will be adding a contributor role for every collaborator in a space. However, the existing design disallows use of Assign API if the user isn't already a part of the space.
This PR adds an exception to the above rule if the service account token is passed. After migration, these changes can be safely reverted.
=>  Allow assignment of role even if user not in space, using service account

controller/collaborators.go, controller/collaborators_blackbox_test.go
We can't check if the current identity has permissions to list collaborators because it breaks the existing collaborators API: Currently Planner requires the list of collaborators to show Planner.
Until Planner is fixed we have to allow any user to list collaborators.
=> Fix collaborators API

controller/collaborators.go, controller/collaborators_blackbox_test.go, controller/resource_roles.go, controller/resource_roles_blackbox_test.go
- This temporary change ensures that for spaces created between 
https://github.com/fabric8-services/fabric8-auth/commit/d79703ccb0f5215d9d077eaf3c1c1705701914a5
and 
https://github.com/fabric8-services/fabric8-auth/commit/837cd5e7b3c976fc18a31d05c475b81db2b82e4c
'List Collaborators' works normally.
- This PR also takes care of https://github.com/fabric8-services/fabric8-auth/pull/512#discussion_r194866234 in the same PR
Even though the changes are semi-related, they would both be reverted after the space migration is complete.
=> Use keycloak permissions for List Collaborators API

controller/token.go, controller/token_blackbox_test.go, controller/user.go, controller/userinfo.go, controller/users.go, goamiddleware/jwt_token_context.go, goamiddleware/jwt_token_context_whitebox_test.go, token/token.go, token/token_test.go
This PR is required to fix the backend side of https://github.com/openshiftio/openshift.io/issues/3746
Also part of https://github.com/openshiftio/openshift.io/issues/3736
=> Add WWW-Authenticate: LOGIN header to the error response when login is required

account/service/user.go, account/service/user_blackbox_test.go, application/service/factory/service_factory.go, application/service/services.go, controller/namedusers.go, controller/namedusers_blackbox_test.go, controller/users.go, controller/users_blackbox_test.go, design/account.go, gormapplication/application.go, main.go, test/account.go, test/graph/test_graph.go, test/graph/user_wrapper.go
Old (being removed) API - https://github.com/fabric8-services/fabric8-auth/pull/354:
```
PATCH /api/users/:id
{
"data": {
"type": "identities",
"attributes": {
"deprovisioned": true
}
}
```
New API:
```
PATCH /api/namedusers/:username/deprovision
Authorization: bearer ${oso_reg_sa_token}
(No Payload)
```
Returns 200 OK if succeed.
Example:
```
PATCH https://auth.openshift.io/api/namedusers/johnsmith/deprovision
Authorization: bearer ${oso_reg_sa_token}
```
This refactoring is needed because the OSO reg app doesn't have OSIO Identity ID available. So, we have to look up the identity by username.
=> Refactor deprovisioning API

README.adoc
The list of files that can be edited is outdated. The README also lists files which are generated.
Instead of listing all the files that can be edited (I assume the list is longer now), this PR updates the instructions to not edit the generated files.
=> README: Update list of files which can be edited

notification/service/notification.go
I noticed that we didn't set request ID in the notification service. This PR fixes that. 
It's very tricky to test this change though.
In our tests we set context via client package and it works. But in runtime a different key is used to store the request ID in the context (middleware vs. client).
So, no tests unfortunately.
=> Forward request ID when calling notification service

Makefile
- For macOS dep package was updated with a new SHA. This SHA value is checked in `Makefile` with a hardcoded SHA checksum to verify dep package. 
- Updated the SHA value to new one.
- Added initialization of `$(UNAME_S)` variable `UNAME_S=$(shell uname -s)` since it was being used but never set which lead to explicitly exporting the variable from shell.
Note: We can probably look into automating the process where SHA value is fetched dynamically instead of hard coding.
=> Updated SHA checksum for dep-darwin-amd64

Gopkg.lock, notification/service/notification.go, notification/service/notification_whitebox_test.go, test/token/token.go
Notification service needs to be called using a service account token, instead of a user account token - for the user's email updation verification email.
This is needed because of notification-service side changes in https://openshift.io/openshiftio/openshiftio/plan/detail/2646
=> Pass service account token to notification service client/req

.make/Makefile.dev, Dockerfile.dev, Makefile, minishift/dev_setup.md, minishift/openshift/auth.app.yaml, minishift/openshift/auth.config.yaml, minishift/openshift/auth.db.yaml, minishift/openshift/fabric8-ui.app.yaml, minishift/openshift/wit.app.yaml, minishift/openshift/wit.config.yaml, minishift/openshift/wit.db.yaml
Adds following make target for minishift local setup for running auth,wit, ui
- **auth:**
- `deploy-auth`
- `deploy-auth-secrets`
- `deploy-auth-db`
- `deploy-auth-only`
- `clean-auth`
- `redeploy-auth`
- **wit:**
- `deploy-wit`
- `deploy-wit-secrets`
- `deploy-wit-db`
- `clean-wit`
- **f8ui**:
- `deploy-f8ui`
- `clean-f8ui`
- **all**:
- `clean-all`
- `clean-all-resources`
- **container/openshift**:
- `build-image`
- `expose-minishift-docker-env`
- `init-project`
Fixes: #551
=> chore(#551): adds dev setup using openshift template and few make target

authorization/role/service/role_management_service_blackbox_test.go, controller/collaborators.go, controller/collaborators_blackbox_test.go
The `Add Collaborators` used to return an error ( non 200 ) if one or more users being added was already a contributor. 
This PR ensures that if a user is already a contributor, the API does not complain and returns a 200, after logging the info that the user is already a contributor. This is analogous to any update API which overwrites existing data even if nothing has changed.
Fixes https://github.com/fabric8-services/fabric8-auth/issues/556
Related to https://github.com/openshiftio/openshift.io/issues/4011
=> If user is already a collaborator, log and move on

controller/token.go, controller/token_blackbox_test.go, design/token.go
For the OAuth2 workflow of the login scenario, we already check if the user is provisioned, however, we were not redirecting the user to the 'not-approved' page if user wasn't provisioned in OSO via the reg-app.
This PR fixes that.
This specific workflow is used only by  che.openshift.io 
So if a user tried to login to che.openshift.io , the server returned a 500 which was a panic caused by a missing nil check - this PR introduces the necessary nil check, and the redirect.
```
{"POST":"/api/token","action":"Exchange","ctrl":"token","from":"106.201.115.98","level":"info","msg":"request started","pkg":"log.LogRequest.func1","req_id":"hhoGiRGUbb-20628","time":"2018-07-25 02:58:23"}
--
  | {"err":"user 'shbose-24062018' is not approved","file":"/tmp/go/src/github.com/fabric8-services/fabric8-a …
```
=> During oauth2 code-token exchange, handle user-not-provisioned scenario

configuration/defaults.go
Needed to be able to test the che login workflow using the devcluster che deployment which @davidfestal is working on. 
This would be used in prod for a short while. prod-preview doesn't help because account provisioning is not automatic.
Change will be reverted.
=> Temporary whitelist of dev cluster url

notification/service/notification.go, wit/service/wit_service.go
It's a cosmetic thing but still...
Instead of using multiple receiver names we should use the same name within a type according to Golang convention. Affected services: notification and WIT.
=> Use the same receiver name within a service

.make/Makefile.dev, minishift/dev_setup.md, minishift/openshift/auth.config.yaml, minishift/openshift/f8notification.app.yaml, minishift/openshift/f8notification.config.yaml
- Adds openshift template for notification
- Adds make target for `deploy-notification`, `clean-notification`.
- Adds documentation about the same
Fixes: #587
=> docs(#587): add documentation for deploying notification on minishift

README.adoc, account/repository/verification_code_blackbox_test.go, authorization/invitation/repository/invitation_blackbox_test.go, authorization/resourcetype/repository/resource_type_scope_blackbox_test.go, authorization/role/repository/identity_role_blackbox_test.go, authorization/role/repository/role_blackbox_test.go, authorization/role/repository/role_scope_blackbox_test.go, authorization/token/repository/token_blackbox_test.go, configuration/configuration.go, gormtestsupport/db_test_suite.go
Use `AUTH_CLEAN_TEST_DATA=false` to keep the DB data after the tests (by
default, all data will be cleaned after each test)
Use `AUTH_ENABLE_DB_LOGS=true` to print all SQL queries in the console (by
default, SQL queries won't be displayed anymore)
Fixes #591
=> Use environment variables to log SQL queries in tests and keep data in DB (#591)

account/repository/identity_blackbox_test.go, application/application_db_calls_bench_test.go, application/service/services.go, application/transaction/transaction_bench_test.go, authorization/authorization.go, authorization/invitation/repository/invitation_blackbox_test.go, authorization/invitation/service/invitation_service_blackbox_test.go, authorization/resource/service/resource_service.go, authorization/resource/service/resource_service_blackbox_test.go, authorization/role/repository/default_role_mapping_blackbox_test.go, authorization/role/repository/identity_role_blackbox_test.go, authorization/role/repository/role_mapping_blackbox_test.go, authorization/role/service/role_management_service.go, authorization/role/service/role_management_service_blackbox_test.go, authorization/space/service/space_service_blackbox_test.go, authorization/team/service/team_service_blackbox_test.go, controller/resource_roles.go, controller/resource_roles_blackbox_test.go, controller/space_blackbox_test.go, controller/team_blackbox_test.go, design/role.go, gormtestsupport/db_test_suite.go, test/graph/organization_wrapper.go, test/graph/space_wrapper.go, test/graph/team_wrapper.go, test/graph/test_graph.go
Added endpoint as /api/resources/:resourceID/scopes/:scopeName
Also:
- refactored `controller/resource_roles_blackbox_test.go` by
grouping in subtests
Fixes #492
=> Add API to to check if a user has a specific scope (#492)

account/repository/user_blackbox_test.go, authorization/role/repository/role_blackbox_test.go, controller/users_blackbox_test.go, wit/service/wit_service_whitebox_test.go
=> fix(#603): replace `s.T()` with `t` for  subtests

.ike-prow/test-keeper.yaml
In Ike-Prow we have a feature where we can add our customized location to skip test check. http://arquillian.org/ike-prow-plugins/#test-keeper-config
Currently, ike is crying each time if we change something in `minishift/` folder. so reviewer has to comment `ok-without-test`.
After this ike won't check for tests with change in all paths mentioned in config file.(in our case `minishift` so no more `ok-without-tests` if any change in `minishift/`).
=> chore: add config file to skip validation for minishift folder

controller/user.go, controller/user_blackbox_test.go
Replace `spaces` with `openshift.io/resource/space` as
the resource type for spaces so there's no need for
a transation from `spaces`, but keep checking the `type`
query param for invalid values, to avoid
running an expensive query for nothing (and then return
a 400 error)
Also, `openshift.io/resource/space` is a valid query param
as defined in https://tools.ietf.org/html/rfc3986#section-3.4,
even if it contains `/` characters
Fixes #623
=> Use existing type as query param for listing resources a user has a role in

.gitignore, Makefile, controller/token.go, login/service.go, login/service_blackbox_test.go, token/token.go
Fill the `session_state` claim of the generated access token
with a random UUID
Fixes #667
=> Missing `session_state` in generated token (#667)

cico_build_deploy.sh
check for f8-auth logs [link](https://ci.centos.org/view/Devtools/job/devtools-fabric8-auth-build-master/351/consoleFull), and search for `make docker-start`, you will find two times .. this PR fix it.
basically cico_build_deploy.sh run twice; one for "rhel" target and other for "non-rhel" target.
=> fix: cico deploy execute some target two times

.gitignore, authorization/role/repository/identity_role_blackbox_test.go, controller/resource_roles_blackbox_test.go, migration/migration.go, migration/migration_blackbox_test.go, migration/sql-files/040-identity-role-index.sql, migration/sql-test-files/040-identity-role-index.sql
when an identity/role/resource relationship was deleted, it was
impossible to re-create the same due to a unique index that would
not ignore the `soft deleted` records.
fixes #718
=> fix: unable to recreate identity/role/resource relationship

authentication/provider/service/authentication_provider_service.go, authentication/provider/user_profile.go, controller/token.go, controller/token_blackbox_test.go
This PR uses the context to propagate username information up the stack from the user profile call (in the authentication service provider) to the token controller, where it is then used to generate the error message returned to the client.
Fixes #683
=> Add username to authentication error message

application/service/services.go, authentication/account/service/user.go, authentication/account/service/user_blackbox_test.go, controller/users.go, controller/users_blackbox_test.go
If some user was manually deprovisioned in the OSO registration app but was not blocked (due to inactivity for example) then the user can reactivate the account by using signup again. In this case the reg app will call Auth to create a new user. Currently Auth will return 409 for such users. This PR re-provision such users and returns 200 to the reg app.
=> Re-provision user by reg app request

application/service/services.go, cluster/cache.go, cluster/cluster.go, cluster/factory/cluster_cache_factory.go, cluster/service/cache.go, cluster/service/cluster.go, cluster/service/cluster_blackbox_test.go, controller/users.go, controller/users_blackbox_test.go, test/clusterservice.go, test/data/cluster/link_identity_to_cluster.yaml, test/data/cluster/unlink_identity_to_cluster.yaml, test/recorder/cluster.go, test/recorder/notification.go, test/recorder/recorder.go
=> feat: call cluster service to create identity cluster relation while creating user

authorization/token/repository/token.go, authorization/token/repository/token_blackbox_test.go, authorization/token/service/token_service.go
Fixes #765 
This PR adds a new method to the token repository, `SetStatusFlagsForIdentity()` which allows the bulk update of token status flags for an identity.  The logout service now uses this method instead of updating token status values individually, which should hopefully result in a performance improvement.
=> Bulk update token status values

application/service/services.go, authorization/token/repository/token.go, authorization/token/repository/token_blackbox_test.go, authorization/token/service/token_service.go, authorization/token/worker/token_cleanup_worker.go, authorization/token/worker/token_cleanup_worker_blackbox_test.go, configuration/configuration.go, configuration/defaults.go, main.go, test/graph/token_wrapper.go
Fixes #767 
This PR introduces a token cleanup worker that runs inside a go routine.  It routinely (once per hour) invokes a token cleanup routine that removes expired tokens after a configurable retention period, set by the `AUTH_EXPIRED_TOKEN_RETENTION_HOURS` configuration parameter, which has a default of 24 hours.
=> Add token cleanup worker

application/service/services.go, authentication/provider/service/authentication_provider_service_blackbox_test.go, authorization/token/repository/token_blackbox_test.go, authorization/token/service/token_service.go, authorization/token/service/token_service_blackbox_test.go, authorization/token/token.go, authorization/token/token_blackbox_test.go, controller/token_blackbox_test.go, goamiddleware/jwt_token_context.go, goamiddleware/jwt_token_context_whitebox_test.go, main.go, test/graph/token_wrapper.go
This PR adds a validation check to the goa middleware to ensure that user access tokens are currently valid.
=> Add token validation check to goa middleware

application/service/services.go, authentication/account/repository/user.go, authentication/account/service/user.go, authentication/account/service/user_blackbox_test.go, migration/migration.go, migration/sql-files/044-user-active.sql, test/account.go, test/graph/user_wrapper.go
Added a new `Active` field on the User type (with an
associated column in the DB with default value 'true')
Obfuscate all personal data in the user and identity records,
and mark the user as `active=false`.
Fixes #775
=> feat(775): obfuscate and deactive user at service layer

cico_run_contract_tests_provider.sh
This PR adds an 'empty' `cico_run_contract_tests_provider.sh` CICO script that is executed by the https://ci.centos.org/job/devtools-contract-test-provider-fabric8-wit-fabric8-auth/ Jenkins job.
The script is empty now to prevent the Jenkins job from failing and will be filled once the proper contract test are merged (https://github.com/fabric8-services/fabric8-auth/pull/711).
=> contract-tests: Add CICO script for provider side of contract testing.

openshift/auth.app.yaml
Currently because of a bug in our template we do not set client ID env var correctly, so we always use the default value which is "fabric8-platform-online". But we have to fix this altogether with updating the corresponding secret when switching to RHD SSO.
**Should be merged only when we update CM/Secrets to switch to RHD!** If we merge it without updating the secrets then incorrect ID will be used.
=> Fix oauth.provider.client.id secret mounting

authentication/account/repository/identity.go, authentication/account/repository/identity_blackbox_test.go, authentication/logout/service/logout_service.go, authentication/provider/service/authentication_provider_service.go, authentication/provider/service/authentication_provider_service_blackbox_test.go, authorization/token/service/token_service.go, authorization/token/service/token_service_blackbox_test.go, controller/logout_blackbox_test.go, goamiddleware/jwt_token_context_whitebox_test.go, migration/migration.go, migration/sql-files/045-identity-last-active.sql
This pull request adds a new timestamp column to the `identities` table:
`ALTER TABLE identities ADD COLUMN last_active timestamp with time zone;`
Upon any of the following the events, this timestamp will be updated to the current time:
- During the authentication process (`authentication_provider_service.go`, in the `CreateOrUpdateIdentityAndUser()` function)
- During refresh token exchange, when a refresh token is exchanged for a renewed access token (in `TokenService.ExchangeRefreshToken()`)
- Upon user logout (in `LogoutService.Logout()`)
Fixes #796
=> Add support for last active timestamp for identities

Makefile, application/service/factory/service_factory.go, application/service/services.go, authentication/account/repository/identity.go, authentication/account/repository/identity_blackbox_test.go, authentication/account/repository/user_blackbox_test.go, authentication/account/service/user.go, authentication/account/service/user_blackbox_test.go, configuration/configuration.go, configuration/defaults.go, test/graph/identity_wrapper.go
user service exposes 2 new methods to:
- list the users to notify before deactivation
- list the users accounts to deactivate for good
the inativity period before notifying and deactiving
are expressed in days and configurable
also, the number of number of identities to retrieve
can be limited (or use '-1' to remove any limit)
Fixes #ODC180
=> List users to deactivate

Gopkg.lock, Gopkg.toml, application/service/services.go, authentication/account/repository/identity.go, authentication/account/repository/identity_blackbox_test.go, authentication/account/service/user.go, authentication/account/service/user_blackbox_test.go, configuration/configuration.go, configuration/defaults.go, gormtestsupport/db_test_suite.go, migration/migration.go, migration/sql-files/048-identity-deactivation-notification.sql, notification/notification.go, test/graph/identity_wrapper.go
Uses the notification service to send a message to the recipients
also, in the tests, setup/teardown before/after each subtest.
Fixes #ODC183
=> Send notification to users before account deactivation

authentication/account/repository/identity.go, authentication/account/repository/identity_blackbox_test.go, migration/migration_blackbox_test.go
done when "touching" the user's "last active" field
fixes #ODC217
=> reset deactivation notification timestamp on user activity

authentication/account/repository/identity.go, authentication/account/repository/identity_blackbox_test.go, authentication/account/service/user_blackbox_test.go, migration/migration.go, migration/sql-files/049-user-banned-index.sql, test/graph/user_wrapper.go
no need to notify and later deactivate users who
were already banned. Even more, their accounts
MUST remain intact, so we can keep a trace of their
ban and prevent them from joining again.
Fixes #ODC359
=> exclude already-banned users from deactivation

application/service/services.go, authentication/subscription/service/oso_subscription_service.go, authentication/subscription/service/oso_subscription_service_blackbox_test.go
Add a method to call the deactivation (aka "deprovision") endpoint on the OpenShift registration app.
fixes #ODC483
=> service method to call Openshift reg app to deactivare a user

authentication/provider/service/authentication_provider_service.go, authentication/provider/service/authentication_provider_service_blackbox_test.go
"escape" the error message which is returned in the query param of the redirect URL
=> Fix TestAuthenticationProviderService/TestInvalidOAuthAuthorizationCode test failure

.make/test.mk, authentication/account/service/user.go, authentication/account/service/user_blackbox_test.go, authentication/account/worker/user_deactivation_worker.go, configuration/configuration.go, configuration/defaults.go, main.go
1. Reverts the test mode introduced by https://github.com/fabric8-services/fabric8-auth/pull/818 (with some fixes)
2. Enables notifications & deactivation workers
3. Sets worker cycles to one hour instead of 4 minutes.
=> Enable user deactivation

Gopkg.lock, authentication/account/service/user.go, authentication/account/service/user_blackbox_test.go, wit/service/wit_service.go, wit/service/wit_service_whitebox_test.go
We should use username, not ID when calling WIT.
This error is not critical. It's just logged and ignored but still worth fixing.
Also, I've changed the order of deactivation. Delete from WIT, Che, Tenant first. If Che fails then return an error. If Tenant fails then return an error. If both Che and Tenant succeed then proceed with removing the user from Auth DB.
=> Fix delete users in WIT

authentication/account/service/tenant.go, authentication/account/service/tenant_whitebox_test.go, authentication/account/service/user_blackbox_test.go, che/service/che_service.go, che/service/che_service_blackbox_test.go, controller/namedusers.go, controller/namedusers_blackbox_test.go
Follow up on https://github.com/fabric8-services/fabric8-auth/pull/834#discussion_r280301696
User could be deactivated/deleted partially. For example in Che we succeed but failed in Tenant. In this case reg app will reschedule deactivation. So, we want to ignore not found errors in the flow (just log them) otherwise re-deactivation won't ever succeed.
=> Don't fail deactivation if user not found

Gopkg.lock, Gopkg.toml
https://github.com/cirello-io/pglock/pull/1 has been fixed and released in v.1.2.1
So, we can switch to the upstream release now.
=> Update gplock to v1.2.1

application/service/services.go, authentication/account/service/user.go, authentication/account/service/user_blackbox_test.go, authentication/account/worker/user_deactivation_notification_worker_test.go, metric/metric_test.go, notification/service/notification.go, notification/service/notification_whitebox_test.go
We should call notification service synchronously from deactivation notification worker. Otherwise we will mark the user as successfully notified even if we got an error from the notification service.
=> Sync call to notification service when notifying inactive users

Gopkg.lock, Gopkg.toml, authentication/account/service/user.go
Fixes https://jira.coreos.com/browse/ODC-754
This pull request simply removes the worker pool from the `NotifyIdentitiesBeforeDeactivation()` function and instead invokes the notification action synchronously.
=> Remove worker pool from user deactivation notification worker

Gopkg.lock, metric/metric.go
Counter type metrics (as inferred from names like _total) are automatically rate-converted to Hz by pcp.
If we rename the counter metrics away from *_total then the row counter should be available in pcp.
=> Remove _total from counter metric names to avoid conversion to Hz

metric/metric.go
Log when the deactivation counter is incremented, just like we do for the deactivation notification counter
=> log when deactivation counter metric is incremented

authentication/account/service/user.go
Change level to `WARN` as we just log the error that occurred on WIT anyways.
=> change level of message when deactivation fails in WIT

cico_build_deploy.sh
We are using `FABRIC8_HUB_TOKEN` to push newly generated client for `fabric8-auth-client` repository.
Currently, it's prompting for password due to which cico job is waiting and ending with failed.
Commenting this to deploy latest master on prod preview, we can uncomment this once this issue is resolved.
=> remove push client as FABRIC8_HUB_TOKEN is prompting for password

Gopkg.lock, authentication/account/repository/identity.go, authentication/account/repository/identity_blackbox_test.go, controller/namedusers.go, migration/migration.go, migration/sql-files/053-deactivation-indexes.sql
Filter users to notify and deactivate by IDP, since this is what we also do when performing the deactivation (and banning)
Also, change a log message to match the same usual pattern: `error while ...`, which makes searching in the logs more consistent.
=> filter users to deactivate by IDP

Gopkg.lock, Gopkg.toml, Makefile, adminconsole/service/admin_console.go, adminconsole/service/admin_console_blackbox_test.go, application/service/factory/service_factory.go, application/service/services.go, authentication/account/service/user.go, authentication/account/service/user_blackbox_test.go, configuration/configuration.go, configuration/defaults.go, gormapplication/application.go, metric/metric_test.go
add admin console service client
include Admin Console service in service factory
use admin console client to create audit log upon notification and deactivation
fixes #ODC760
=> create audit logs upon notification and deactivation

authentication/account/service/user.go, authentication/account/service/user_blackbox_test.go
fix to avoid submitting the request with the
obfuscated username :/
=> user real username when creating audit log

authentication/account/repository/identity.go, authentication/account/repository/identity_blackbox_test.go, authentication/account/service/user.go, authentication/account/service/user_blackbox_test.go, configuration/configuration.go, configuration/configuration_blackbox_test.go, metric/metric_test.go, openshift/auth.app.yaml, openshift/auth.config.yaml
Use a configuration-based list of usernames to exclude from the user deacvation. 
It's enough if those users are not notified: they won't have a scheduled deactivation either.
Fixes #ODC1007
=> add whitelist to exclude user from deactivation

authorization/token/manager/token_manager.go, authorization/token/manager/token_manager_test.go, authorization/token/manager/token_manager_whitebox_test.go, configuration/configuration.go, configuration/configuration_blackbox_test.go, controller/token_blackbox_test.go, goamiddleware/jwt_token_context_whitebox_test.go, rest/rest.go, rest/rest_blackbox_test.go
- **remove usage of http request** in method `GenerateUnsignedUserAccessTokenForIdentity()`.  Such method ideally no need to have request in given context.  Out of http request only AuthServiceURL is extracted which is now taken from `config.GetAuthServiceURL()`
- introduce new method `ReplaceDomainPrefixInAbsoluteURLStr()` in rest package, which works upon URL string input and does similar to what ReplaceDomainPrefixInAbsoluteURL() doing.
- config.GetAuthServiceURL() return `http://auth.localhost` instead of `http://localhost` for default case when it called from localhost while running test.  We need to add `auth` sub-domain so that  GenerateUnsignedUserAccessTokenForIdentity() test run smoothly.  Also, auth_service_url will be always having sub-domain (in prod and prod-preview) and …
=> remove usage of request in generate token methods

authentication/account/worker/user_deactivation_worker.go, authentication/account/worker/user_deactivation_worker_test.go, authentication/subscription/service/oso_subscription_service.go, authentication/subscription/service/oso_subscription_service_blackbox_test.go
- handle HTTP 404 from reg_app and call userService.DeactivateUser() directly from user_deactivation_worker.
- enhance existing user_deactivation_worker test to actually trigger user_deativation during test run.
- added new test in user_deactivation_worker for 404 case.
=> handling reg app HTTP 404 user not found

jsonapi/jsonapi_utility.go, main.go
Our sentry service is moving to another location. Let's disable it for now. We might want to migrate to the new server later.
=> Disable sentry

Makefile, authentication/provider/repository/state.go, authentication/provider/repository/state_blackbox_test.go, authentication/provider/worker/state_cleanup_worker.go, authentication/provider/worker/state_cleanup_worker_test.go, configuration/configuration.go, configuration/defaults.go, main.go, migration/migration.go, migration/migration_blackbox_test.go, migration/sql-files/054-cleanup-oauth-state-references.sql, migration/sql-test-files/054-cleanup-oauth-state-references.sql
The worker is configured to run every hour (configurable)
and delete all OAuth state references older than 24hrs (hard-coded).
The worker is based on the same implementation as the other workers
(for user deactivation) and thus runs in a go routine and uses
a lock to prevent concurrent executions (although, in this case,
it's not a big deal)
Also, include a migration step to remove all OAuth state refs
older than 24hrs during startup, using a DB migration script.
Fixes https://issues.redhat.com/browse/CRT-539
=> add worker to cleanup old OAuth State References

authentication/provider/worker/state_cleanup_worker.go
Fixing the wrong message when the OAuth state reference cleanup worker starts.
See https://github.com/fabric8-services/fabric8-auth/pull/866#discussion_r420213723 
=> fix worker start message

authentication/provider/repository/state.go, authentication/provider/repository/state_blackbox_test.go, authentication/provider/worker/state_cleanup_worker.go, configuration/defaults.go, migration/migration_blackbox_test.go, migration/sql-files/054-cleanup-oauth-state-references.sql, migration/sql-test-files/054-cleanup-oauth-state-references.sql
- abandon the migration step because there are too many
records to delete (timeout)
- rely solely on the worker, which deletes the old records
by chunk of 1000
- run the worker every 10min
Updates https://issues.redhat.com/browse/CRT-539
=> refactor OAuth State Reference cleanup
